main:
	gcc ex2.c -o ex2

test: 
	./ex2 samples/rand_int.txt dec
	./ex2 samples/rand_int.txt inc
	./ex2 samples/rand_int.txt rand
	./ex2 samples/rand_double.txt dec
	./ex2 samples/rand_double.txt inc
	./ex2 samples/rand_double.txt rand
	./ex2 samples/rand_char.txt dec
	./ex2 samples/rand_char.txt inc
	./ex2 samples/rand_char.txt rand